routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/','App\Http\Controllers\HomePage@index')->name('HomePage');

Route::resource('person','App\Http\Controllers\PersonController');
Route::resource('address','App\Http\Controllers\AddressController');

app/Models/Addres.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Addres extends Model
{
    use HasFactory;

}

app/Models/Personel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Personel extends Model
{
    use HasFactory;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/AddressController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Addres;
use App\Models\Personel;
use Illuminate\Support\Facades\DB;

class AddressController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Address=DB::table('personels')
        ->join('addres','personels.id','=','addres.person_id')
        ->get();

        return view('front/address/index',compact('Address'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $Adres=new Addres();
        $Adres->person_id=$request->person_id;
        $Adres->address=$request->address;
        $Adres->post_code=$request->post_code;
        $Adres->city_name=$request->city_name;
        $Adres->country_name=$request->country_name;
        $Adres->save();

        return redirect('address');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $Person=Personel::find($id);

        return view('front/address/create',compact('Person'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $Adres=DB::table('personels')
            ->join('addres','personels.id','=','addres.person_id')
            ->where('addres.id',$id)
            ->first();

        return view('front/address/edit',compact('Adres'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $Adres=Addres::find($id);
        $Adres->address=$request->address;
        $Adres->post_code=$request->post_code;
        $Adres->city_name=$request->city_name;
        $Adres->country_name=$request->country_name;
        $Adres->save();

        return redirect('address');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Addres::destroy($id);

        return redirect('address');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomePage.php
<?php

namespace App\Http\Controllers;

use App\Models\Addres;
use App\Models\Personel;

use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;

class HomePage extends Controller
{
    //HomePage
    public function index(){

        $Persons=Personel::all();
        $Address=Addres::count();

        return view('front/index',compact('Persons','Address'));

    }
}

app/Http/Controllers/PersonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Addres;
use App\Models\Personel;

class PersonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Persons=Personel::all();

        return view('front/person/index',compact('Persons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('front/person/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        //Create Person

        $Person=new Personel();
        $Person->name=$request->name;
        $Person->birthday=$request->birthday;
        $Person->gender=$request->gender;
        $Person->save();

        return redirect('/person');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        //Person
        $Person=Personel::findOrFail($id);
        $Address=Addres::where('person_id',$id)->orderByDesc('id')->paginate(5);

        return view('front/person/show',compact('Person','Address'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->birthday==NULL){
            $birthday=$request->birthdaycurrent;
        }else{
            $birthday=$request->birthday;
        }

        $Person=Personel::find($id);
        $Person->name=$request->name;
        $Person->birthday=$birthday;
        $Person->gender=$request->gender;
        $Person->save();


        return redirect("person/$id");

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/front/address/edit.blade.php
@extends('front.layouts.master')
@section('TitlePage',"Addres Edit")
@section('content')
    <div class="page-wrapper" style="margin-top:-4%">
        <!-- Person View -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h3 class="page-title text-truncate text-dark font-weight-medium mb-1 text-black-50">Address Edit</h3>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3  col-md-12">
                    <div class="card text-center bg-white">
                        <strong style="font-size: 4rem" >{{$Adres->id}}</strong>
                        <p class="small">Address No</p>
                    </div>
                    <div class="card p-3">
                        <p class=" small"> <i class="fa fa-info-circle text-warning "></i>
                            Click on the <b>Update</b> button after making the relevant changes.</p>
                    </div>
                </div>

                <!--person ınfo -->
                <div class="col-lg-9 col-md-12">
                   <!--Address Delete -->
                   <form method="post" action="{{route('address.destroy',$Adres->id)}}">
                       @csrf
                       @method('delete')
                       <div class="card">
                           <button type="submit"  class="btn btn-default btn-sm form-control text-black-50"  ><strong>Delete Address</strong></button>
                       </div>
                   </form>


                    <div class="card">
                        <div class="card-body">
                            <form method="post" action="{{route('address.update',$Adres->id)}}">
                                @method('put')
                                @csrf
                                <table class="table table-sm border-0 small">
                                    <tr>
                                        <td>Name</td>
                                        <td>{{$Adres->name}}</td>
                                    </tr>
                                    <tr>
                                        <td>Address</td>
                                        <td>
                                            <textarea type="text" name="address" minlength="10"  maxlength="150" class="form-control form-control-sm " >{{$Adres->address}}</textarea>
                                        </td>
                                    </tr>
                                    <tr >
                                        <td>Post Code</td>
                                        <td ><input type="text" name="post_code" value="{{$Adres->post_code}}"  class="form-control form-control-sm " ></td>
                                    </tr>
                                    <tr>
                                        <td>City Name</td>
                                        <td><input type="text" name="city_name" value="{{$Adres->city_name}}" maxlength="40" class="form-control form-control-sm"></td>
                                    </tr>
                                    <tr>
                                        <td>Country Name</td>
                                        <td><input type="text" name="country_name" value="{{$Adres->country_name}}" maxlength="50" class="form-control form-control-sm"></td>
                                    </tr>
                                    <tr>
                                        <td>Created Date</td>
                                        <td>{{$Adres->created_at}}</td>
                                    </tr>
                                    <tr>
                                        <td>Updated Date</td>
                                        <td>{{$Adres->updated_at}}</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td >
                                            <button type="submit" class="btn btn-default text-center btn-sm form-control"  name="update"><strong>Update</strong></button>
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/front/address/index.blade.php
@extends('front.layouts.master')
@section('TitlePage','Address Lists')
@section('content')
    <div class="page-wrapper" style="margin-top:-4%">
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center ">
                    <h3 class="page-title text-truncate text-black-50 font-weight-medium mb-1">Address</h3>
                    <div class="d-flex align-items-center">
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="card p-2 text-right bg-banner">
                <a href="{{route('person.create')}}">
                    <span class="opacity-7 text-muted "> <h5 class="  font-weight-medium"><i data-feather="plus"></i> New Person Create</h5></span>
                </a>
            </div>

            <!--Person List -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-center mb-4">
                                <h4 class="card-title text-black-50">Address</h4>
                                <div class="ml-auto">
                                </div>
                            </div>

                            <div class=" table table-responsive-lg">
                                <table id="persons" class="table  table-bordered  small">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Address</th>
                                        <th>Post Code</th>
                                        <th>City</th>
                                        <th>Country</th>
                                        <th>Created Date</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($Address as $adres)
                                        <tr>
                                            <td>{{$adres->id}}</td>
                                            <td>{{$adres->name}}</td>
                                            <td>{{$adres->address}}</td>
                                            <td>{{$adres->post_code}}</td>
                                            <td>{{$adres->city_name}}</td>
                                            <td>{{$adres->country_name}}</td>
                                            <td>{{$adres->created_at}}</td>
                                            <td class="text-center" title="Edit"><a href="{{route('address.edit',$adres->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-edit text-white"></i></a></td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>

                </div>
            </div>


        </div>
    </div>
@endsection
@section('js')
    <script >
        $(document).ready(function() {
            $('#persons').DataTable();
        } );
    </script>
    <script src="{{asset('front/')}}/src/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{asset('front/')}}/src/dist/js/pages/datatable/datatable-basic.init.js"></script>
@endsection

resources/views/front/index.blade.php
@extends('front.layouts.master')
@section('TitlePage','Person ')
@section('content')
    <div class="page-wrapper" style="margin-top:-4%">
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h3 class="page-title text-truncate text-dark font-weight-medium mb-1">Person List</h3>
                    <div class="d-flex align-items-center">
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="card-group">
                <div class="card border-right">
                    <div class="card-body">
                        <div class="d-flex d-lg-flex d-md-block align-items-center">
                            <div>
                                <div class="d-inline-flex align-items-center">
                                    <h2 class="text-dark w-100 mb-1 font-weight-medium">{{count($Persons)}}</h2>
                                </div>
                               <h6 class="badge badge-warning font-weight-normal mb-0 w-100 ">Total Person</h6>
                            </div>
                            <div class="ml-auto mt-md-3 mt-lg-0">
                                <span class="opacity-7 text-muted"><i data-feather="user"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card border-right">
                    <div class="card-body">
                        <div class="d-flex d-lg-flex d-md-block align-items-center">
                            <div>
                                <h2 class="text-dark mb-1 w-100  font-weight-medium"><sup class="set-doller"></sup>{{$Address}}</h2>
                               <h6 class="badge badge-warning font-weight-normal mb-0 w-100  ">Total Address</h6>
                            </div>
                            <div class="ml-auto mt-md-3 mt-lg-0">
                                <span class="opacity-7 text-muted"><i data-feather="database"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <a href="{{route('person.create')}}">
                    <div class="card-body">
                        <div class="d-flex text-center d-lg-flex d-md-block align-items-center">
                                <h5 class="text-black-50 mt-3 mb-1 font-weight-medium">New Person Create</h5>
                            <div class="ml-auto mt-md-3 mt-lg-0">
                                <span class="opacity-7 text-muted"><i data-feather="plus"></i></span>
                            </div>
                        </div>
                    </div>
                    </a>
                </div>
            </div>

            <!--Person List -->
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-center mb-4">
                                <h4 class="card-title text-black-50">Persons</h4>
                                <div class="ml-auto">
                                </div>
                            </div>

                            <div class=" table table-responsive-lg">
                                <table id="persons" class="table  table-bordered  small">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Name</th>
                                        <th>Gender</th>
                                        <th>Birthday</th>
                                        <th>Created Date</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($Persons as $person)
                                        <tr>
                                            <td>{{$person->id}}</td>
                                            <td>{{$person->name}}</td>
                                            <td>{{$person->gender}}</td>
                                            <td>{{$person->birthday}}</td>
                                            <td>{{$person->created_at}}</td>
                                            <td class="text-center" title="View"><a href="{{route('person.show',$person->id)}}" class="btn btn-primary btn-sm"><i class="fa fa-eye text-white"></i></a></td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>

                            </div>

                        </div>
                    </div>

                </div>
            </div>


        </div>
    </div>
@endsection
@section('js')
    <script >
        $(document).ready(function() {
            $('#persons').DataTable();
        } );
    </script>
    <script src="{{asset('front/')}}/src/assets/extra-libs/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="{{asset('front/')}}/src/dist/js/pages/datatable/datatable-basic.init.js"></script>
@endsection

resources/views/front/layouts/header.blade.php
<!DOCTYPE html>
<html dir="ltr" lang="tr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="test">
    <meta name="author" content="test">
    <title>BackEnd Test @yield('TitlePage')</title>
    <!-- Custom CSS -->

    <link href="{{asset('front/')}}/src/assets/extra-libs/jvector/jquery-jvectormap-2.0.2.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="{{asset('front/')}}/src/dist/css/style.min.css" rel="stylesheet">
    <link href="{{asset('front/')}}/src/assets/extra-libs/datatables.net-bs4/css/dataTables.bootstrap4.css" rel="stylesheet">
</head>
<body>
<div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
     data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
    <!-- ============================================================== -->
    <!-- Topbar header - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <header class="topbar" data-navbarbg="skin6" style="height: 40px">
        <nav class="navbar top-navbar navbar-expand-md" >
            <div class="navbar-header" data-logobg="skin6">
                <!-- This is for the sidebar toggle which is visible on mobile only -->
                <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i
                        class="ti-menu ti-close"></i></a>
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-brand text-center">
                    <!-- Logo  -->
                    <a href="/">
                        <b class="logo-icon">
                            <!--  Logo  -->
                            <img src="{{asset('front/')}}/src/assets/images/mynet.png" alt="logo" class="dark-logo" width="110" height="60" />
                        </b>
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <aside class="left-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar" data-sidebarbg="skin6">
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" href="{{route('HomePage')}}" aria-expanded="false">
                            <i data-feather="home" class="feather-icon"></i>
                            <span class="hide-menu">Home</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" href="{{route('person.index')}}" aria-expanded="false">
                            <i data-feather="user" class="feather-icon"></i>
                            <span class="hide-menu">Persons</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" href="{{route('address.index')}}" aria-expanded="false">
                            <i data-feather="database" class="feather-icon"></i>
                            <span class="hide-menu">Address</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
    </aside>

resources/views/front/layouts/master.blade.php
@include('front.layouts.header')
@yield('content')
@include('front.layouts.footer')

resources/views/front/person/show.blade.php
@extends('front.layouts.master')
@section('TitlePage',"Person View")
@section('content')
    <div class="page-wrapper" style="margin-top:-4%">
        <!-- Person View -->
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-7 align-self-center">
                    <h3 class="page-title text-truncate text-dark font-weight-medium mb-1 text-black-50">Person View</h3>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-3  col-md-12">
                    <div class="card text-center bg-white">
                            <strong style="font-size: 4rem" >{{$Person->id}}</strong>
                        <p class="small">Person No</p>
                    </div>
                    <div class="card text-center">
                        <p class="small" >Created Date</p>
                        <strong class="text-black-50 small" >{{$Person->created_at}}</strong>
                        <hr>
                        <p class="small" >Updated Date</p>
                        <strong class="text-black-50 small"  >{{$Person->updated_at}}</strong>
                    </div>
                </div>

                <!--person ınfo -->
                <div class="col-lg-9 col-md-12">
                    <!--Address Add -->
                    <div class="card">
                            <a href="{{route('address.show',$Person->id)}}"  class="btn btn-default btn-sm form-control text-black-50"  ><strong>Add Address</strong></a>
                    </div>

                    <div class="card">
                        <div class="card-body">
                            <form method="post" action="{{route('person.update',$Person->id)}}">
                                @method('put')
                                @csrf
                            <table class="table table-sm border-0 small">
                                <tr>
                                    <td colspan="2"><input type="text" name="name" value="{{$Person->name}}" maxlength="30" class="form-control form-control-sm "></td>
                                </tr>
                                <tr class="text-center">
                                    <td ><input type="date" name="birthday"  class="form-control form-control-sm border-0"></td>
                                    <td><input type="text" name="birthdaycurrent" value="{{$Person->birthday}}" hidden>{{$Person->birthday}}</td>
                                </tr>
                                <tr class="text-center">
                                    <td >
                                        <select class="form-control form-control-sm border-0" name="gender">
                                            <option value="{{$Person->gender}}">Change Gender</option>
                                            @if($Person->gender=="male")
                                                <option value="female">Female</option>
                                            @else
                                                <option value="male">Male</option>
                                            @endif
                                        </select>
                                    </td>
                                    <td>{{$Person->gender}}</td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="text-center">
                                        <button type="submit" class="btn btn-default text-center btn-sm form-control"  name="update"><strong>Update</strong></button>
                                    </td>
                                </tr>
                            </table>
                            </form>
                        </div>

                    </div>

                    <!--Address -->
                    @foreach($Address as $adres)
                    <div class="card">
                        <div class="row">

                            <div class="col-lg-2 col-md-12">
                                <div class="card text-center ">
                                 <div class="card-body bg-banner">
                                    <strong style="font-size: 2rem">{{$adres->id}}</strong>

                                 </div>
                                    <a href="{{route('address.edit',$adres->id)}}" class="btn btn-secondary btn-sm"><i class="fa fa-edit text-white"></i></a>
                                </div>
                            </div>

                            <div class="col-lg-10 col-md-12">

                                <div class="card">
                                    <div class="card-body">
                                        <table class="table table-sm small">
                                            <tr>
                                                <td colspan="2" >{{$adres->address}}</td>
                                            </tr>
                                            <tr>
                                                <td colspan="2">{{$adres->post_code}}</td>
                                            </tr>
                                            <tr>
                                                <td>{{$adres->city_name}}</td>
                                                <td>
                                                    {{$adres->country_name}}
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>Created Date: {{$adres->created_at}}</td>
                                                <td>Updated Date: {{$adres->updated_at}}</td>
                                            </tr>

                                        </table>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                    @endforeach
                    <div class="pagination flex-m flex-w p-t-26">
                        {{$Address->links("pagination::bootstrap-4")}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection